global using System;
global using System.Collections.Generic;
global using System.Text;
global using System.ComponentModel.DataAnnotations;
global using ServerTwin.Enums;
global using ServerTwin.Models;
global using ServerTwin.Interfaces;
global using ServerTwin.Helpers;
global using ServerTwin.AIModels;