function S = ida_split_stats(A, trainIdx, testIdx, varNames)
A = double(A);
Atr = A(trainIdx, :);
Ate = A(testIdx,  :);

S = table(string(varNames(:)), ...
    mean(A, 1, 'omitnan')', std(A, 0, 1, 'omitnan')', min(A, [], 1, 'omitnan')', max(A, [], 1, 'omitnan')', ...
    mean(Atr, 1, 'omitnan')', std(Atr, 0, 1, 'omitnan')', min(Atr, [], 1, 'omitnan')', max(Atr, [], 1, 'omitnan')', ...
    mean(Ate, 1, 'omitnan')', std(Ate, 0, 1, 'omitnan')', min(Ate, [], 1, 'omitnan')', max(Ate, [], 1, 'omitnan')', ...
    'VariableNames', {'Var','Mean_All','Std_All','Min_All','Max_All','Mean_Train','Std_Train','Min_Train','Max_Train','Mean_Test','Std_Test','Min_Test','Max_Test'} );
end
